apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: development-clusters
  namespace: reversewords-app
spec:
  clusterLabels:
    matchLabels:
      env: dev
  clusterReplicas: 1
