apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: development-clusters
  namespace: gitops-apps
spec:
  clusterLabels:
    matchLabels:
      env: "dev"
  clusterReplicas: 1
