apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: production-clusters
  namespace: reversewords-app
spec:
  clusterLabels:
    matchLabels:
      env: "pro"
  clusterReplicas: 1
